# Basic workflow for building and testing the pip installation

name: Continuous Integration

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab


jobs:
  Test:
    name: py${{ matrix.versions.python-version }} ${{ matrix.versions.resolution }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - python-version: 3.10
            resolution: lowest-direct
          - python-version: 3.11
            resolution: highest
          - python-version: 3.12
            resolution: highest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python with uv
        uses: drivendataorg/setup-python-uv-action@v1.0.0
        with:
          python-version: ${{ matrix.versions.python-version }}

      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -e . -r pyproject.toml --extra dev --resolution ${{ matrix.versions.resolution }}

      - name: Execute Tests with Pytest and Coverage
        run: |
          coverage run -m pytest -n auto --doctest-glob="README.md"
          coverage report -m
          coverage xml

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
